### PR TITLE
Fix Firefox style loading delay caused by autofocus and move user menu to navbar

### PR DESCRIPTION
**Pull request by guoyunhe**
This should fix the style loading issues in Firefox <= 57. Also, the login button has been moved to navbar to avoid misclicks.

screenshot_2018-09-01 opensuse

### CODE REVIEW

**Comment by cboltz** [comment]
Thanks, deployed on en-test.o.o! 

I can confirm that the style load issues are fixed. I also like the new place for the login links.

IMHO the updated design looks good and is production-ready :-)  If you agree, I can update the production wikis next weekend (after the wine festival ;-)

**Comment by guoyunhe** [comment]
Sure, let's deploy it!

**Comment by cboltz** [comment]
I just deployed it :-)

As a sidenote - it looks like you also accidently ;-) fixed https://progress.opensuse.org/issues/40505 with the updated skin.

**Comment by guoyunhe** [comment]
It looks good! Thanks!

**Pull request merged**
