### PR TITLE
New skin: template migration and bug fix

### PR DESCRIPTION
**Pull request by guoyunhe**
This pull request fixed several bugs you have mentioned.

Table of content text wrap:
screenshot_20180121_170249

Image icon in Portal:
screenshot_20180121_202724

Search form in wiki text:
screenshot_20180121_205821

Knowledge template:
screenshot_20180121_210252

### CODE REVIEW

**Comment by cboltz** [comment]
Thanks for all the fixes and improvements!

Please have a look at the `Image icon in Portal:` screenshot again - the `&section={{{section}}}}}` text shouldn't be there ;-)

Also, for people like me who are not familiar with gulp and sass, can you please add some instructions how to install and use gulp and sass to "compile" the theme to the README? Bonus points if you add a Makefile so that we can just run `make` to build everything, and `make clean` to delete the autogenerated files ;-) (If you are not familiar with writing Makefiles, no worries - if you provide the needed commands, I can convert them to a Makefile.)

**Comment by guoyunhe** [comment]
> Please have a look at the Image icon in Portal: screenshot again - the &section={{{section}}}}} text shouldn't be there ;-)

I think it is because I miss some templates in my localhost. It should be okay on en-test.opensuse.org.

> Also, for people like me who are not familiar with gulp and sass, can you please add some instructions how to install and use gulp and sass to "compile" the theme to the README? Bonus points if you add a Makefile so that we can just run make to build everything, and make clean to delete the autogenerated files ;-) (If you are not familiar with writing Makefiles, no worries - if you provide the needed commands, I can convert them to a Makefile.)

I will write all steps needed to run gulp build task. Since all compiled JS and CSS are already in git version control, you don't need to run any command when deploy it on server or build RPM package. So I guess a Makefile is not necessary.

**Comment by cboltz** [comment]
I finally had some time for a quick review (whatever "quick" means given the big delay - sorry for that). Your changes look good :-) so I'll merge them.

> I will write all steps needed to run gulp build task. Since all compiled JS and CSS are already in git version control, you don't need to run any command when deploy it on server or build RPM package. So I guess a Makefile is not necessary.

In theory you are right ;-)

In practise, a Makefile would still be a good idea IMHO. Rebuilding everything is easier and faster than copy&paste from the README, and it allows even people who aren't familiar with gulp to do changes easily.

Just as an idea - depending on what is needed to build the "compiled" CSS and JS, it might even be an option to drop the compiled files from git and build them in OBS. (If the build needs to download something, this won't work, but otherwise it should be doable.)

That said - the Makefile and/or README isn't a showstopper, so I'll merge this pull request now ;-)

**Comment by cboltz** [comment]
Deployed on en-test.opensuse.org, looks good :-)

I noticed that the grey background in the left column (navigation) is done - is this an intentional change? (Personally I liked the grey background, but it's probably a matter of taste.)

**Comment by guoyunhe** [comment]
Gulp requires downloading additional tools to build. It can still be wrapped by a Makefile, but it is useless for OBS.

I removed the gray background on left column. The layout of main area is still unfinished. Maybe I will add the background back and change content width again. I found Gitbook is a good example.

https://0xax.gitbooks.io/linux-insides/content/

**Pull request merged**
